export const MONITORING_ENV = {
  databaseUrl: process.env.MONITORING_DATABASE_URL ?? "",
  jwtSecret: process.env.MONITORING_JWT_SECRET ?? process.env.JWT_SECRET ?? "changeme-secret-jwt",
  corsOrigin: process.env.MONITORING_CORS_ORIGIN ?? process.env.CORS_ORIGIN ?? "*",
  publishSecret: process.env.MONITORING_PUBLISH_SECRET ?? "",
  enableProcessor: process.env.MONITORING_PROCESSOR_ENABLED === "true",
  evalIntervalSeconds: Number.parseInt(process.env.MONITORING_EVAL_INTERVAL ?? "3", 10),
  offlineTimeoutSeconds: Number.parseInt(process.env.MONITORING_OFFLINE_TIMEOUT ?? "60", 10),
  alertCooldownSeconds: Number.parseInt(process.env.MONITORING_ALERT_COOLDOWN ?? "120", 10),
  pingEnabled: process.env.MONITORING_PING_ENABLED === "true",
  pingTimeoutSeconds: Number.parseInt(process.env.MONITORING_PING_TIMEOUT ?? "3", 10),
  pingCount: Number.parseInt(process.env.MONITORING_PING_COUNT ?? "1", 10),
  telegramToken: process.env.MONITORING_TELEGRAM_TOKEN ?? process.env.TELEGRAM_TOKEN ?? "",
  telegramChatId: process.env.MONITORING_TELEGRAM_CHAT_ID ?? process.env.TELEGRAM_CHAT_ID ?? "",
  smtpHost: process.env.MONITORING_SMTP_HOST ?? process.env.SMTP_HOST ?? "",
  smtpPort: Number.parseInt(process.env.MONITORING_SMTP_PORT ?? process.env.SMTP_PORT ?? "587", 10),
  smtpUser: process.env.MONITORING_SMTP_USER ?? process.env.SMTP_USER ?? "",
  smtpPass: process.env.MONITORING_SMTP_PASS ?? process.env.SMTP_PASS ?? "",
  alertEmail: process.env.MONITORING_ALERT_EMAIL ?? process.env.ALERT_EMAIL ?? "",
};
